sudo: false
language: cpp
compiler:
  - gcc
addons:
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - catch
script:
  - make mkouts
  - make main
  - make test
  - make run_test