sudo: true
before_install:
  - sudo apt-get install catch
language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
script:
  - make mkouts
  - make main
  - make test
  - make run_test