sudo: true
language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install -y catch
addons:
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
script:
  - make mkouts
  - make main
  - make test
  - make run_test